{
  "main": {
    "id": "c6d6f9155176da6c",
    "type": "split",
    "children": [
      {
        "id": "27e6b7fb5524db87",
        "type": "tabs",
        "children": [
          {
            "id": "13262db20bf3539e",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "diario/2023-01-11.md",
                "mode": "source",
                "source": false
              }
            }
          },
          {
            "id": "33672e1c34a32c08",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "zettels/List comprehension em python.md",
                "mode": "source",
                "source": false
              }
            }
          },
          {
            "id": "88182e49692455bf",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "zettels/Iteráveis e iteradores em python.md",
                "mode": "source",
                "source": false
              }
            }
          },
          {
            "id": "9e77fa1b090db9d7",
            "type": "leaf",
            "state": {
              "type": "markdown",
              "state": {
                "file": "zettels/Tratando exceções em python.md",
                "mode": "source",
                "source": false
              }
            }
          }
        ],
        "currentTab": 3
      }
    ],
    "direction": "vertical"
  },
  "left": {
    "id": "e4b977935d42acab",
    "type": "split",
    "children": [
      {
        "id": "a28ece1dcae6c772",
        "type": "tabs",
        "children": [
          {
            "id": "18aee7fd35dae99c",
            "type": "leaf",
            "state": {
              "type": "file-explorer",
              "state": {
                "sortOrder": "alphabetical"
              }
            }
          },
          {
            "id": "03597af0d72b95c9",
            "type": "leaf",
            "state": {
              "type": "search",
              "state": {
                "query": "",
                "matchingCase": false,
                "explainSearch": false,
                "collapseAll": false,
                "extraContext": false,
                "sortOrder": "alphabetical"
              }
            }
          },
          {
            "id": "330bdfbf38998bc7",
            "type": "leaf",
            "state": {
              "type": "starred",
              "state": {}
            }
          }
        ],
        "currentTab": 1
      }
    ],
    "direction": "horizontal",
    "width": 300
  },
  "right": {
    "id": "20a61bb452eb6f85",
    "type": "split",
    "children": [
      {
        "id": "c145a6f786a3b29a",
        "type": "tabs",
        "children": [
          {
            "id": "f7e19d0aec45fd1d",
            "type": "leaf",
            "state": {
              "type": "tag",
              "state": {
                "sortOrder": "frequency",
                "useHierarchy": true
              }
            }
          },
          {
            "id": "c403ec5d38296556",
            "type": "leaf",
            "state": {
              "type": "calendar",
              "state": {}
            }
          },
          {
            "id": "fe389f536d63387a",
            "type": "leaf",
            "state": {
              "type": "backlink",
              "state": {
                "file": "zettels/Tratando exceções em python.md",
                "collapseAll": false,
                "extraContext": false,
                "sortOrder": "alphabetical",
                "showSearch": false,
                "searchQuery": "",
                "backlinkCollapsed": false,
                "unlinkedCollapsed": true
              }
            }
          },
          {
            "id": "da00b883ec496cba",
            "type": "leaf",
            "state": {
              "type": "outgoing-link",
              "state": {
                "file": "zettels/Tratando exceções em python.md",
                "linksCollapsed": false,
                "unlinkedCollapsed": true
              }
            }
          },
          {
            "id": "c0093c40b5ed3f79",
            "type": "leaf",
            "state": {
              "type": "outline",
              "state": {
                "file": "zettels/Tratando exceções em python.md"
              }
            }
          }
        ],
        "currentTab": 2
      }
    ],
    "direction": "horizontal",
    "width": 289.5,
    "collapsed": true
  },
  "left-ribbon": {
    "hiddenItems": {
      "switcher:Open quick switcher": false,
      "graph:Open graph view": false,
      "canvas:Create new canvas": false,
      "daily-notes:Open today's daily note": false,
      "templates:Insert template": false,
      "command-palette:Open command palette": false
    }
  },
  "active": "9e77fa1b090db9d7",
  "lastOpenFiles": [
    "zettels/Iteráveis e iteradores em python.md",
    "zettels/Tratando exceções em python.md",
    "diario/2023-01-11.md",
    "zettels/Deep web.md",
    "zettels/ahmia.fi.md",
    "diario/2023-01-12.md",
    "README.md",
    "Untitled.md",
    "links nada ave.md",
    "zettels/List comprehension em python.md"
  ]
}